# FROM OpenJDK
ARG JAVA_VERSION=21
FROM openjdk:${JAVA_VERSION}-slim AS build

# Container general settings
VOLUME /data
EXPOSE 19132

# Java Start Options
ENV INIT_MEMORY "1024M"
ENV MAX_MEMORY "1024M"

# this will force a config rewrite every time.
ENV OVERWRITE_CONFIG "false"

# Bedrock server config
ENV BEDROCK_ADDRESS "0.0.0.0"
ENV BEDROCK_PORT "19132"
ENV BEDROCK_CLONE_REMOTE_PORT "false"
ENV BEDROCK_MOTD1 "Geyser"
ENV BEDROCK_MOTD2 "Another Geyser server."
ENV BEDROCK_SERVERNAME "Geyser"
ENV BEDROCK_COMPRESSION_LEVEL "6"
ENV BEDROCK_BROADCAST_PORT "19132"
ENV BEDROCK_ENABLE_PROXY_PROTOCOL "false"

# Remote Server Config (java server)
ENV REMOTE_ADDRESS "auto"
ENV REMOTE_PORT "25565"
ENV REMOTE_AUTH_TYPE "online"
ENV REMOTE_USE_PROXY_PROTOCOL "false"
ENV REMOTE_FORWARD_HOSTNAME "false"

# Ignore if not using floodgate
ENV GEYSER_FLOODGATE_KEY_FILE "key.pem"

# Geyser General Config
ENV GEYSER_PENDING_AUTH_TIMEOUT "120"
ENV GEYSER_COMMAND_SUGGESTIONS "true"
ENV GEYSER_PASSTHROUGH_MOTD "true"
ENV GEYSER_PASSTHROUGH_PLAYER_COUNTS "true"
ENV GEYSER_PASSTHROUGH_INTERVAL "3"
ENV GEYSER_FORWARD_PLAYER_PING "false"

ENV GEYSER_MAX_PLAYERS "100"
ENV GEYSER_DEBUG_MODE "false"
ENV GEYSER_SHOW_COOLDOWN "title"
ENV GEYSER_SHOW_COORDINATES "true"
ENV GEYSER_DISABLE_BEDROCK_SCAFFOLDING "false"
ENV GEYSER_EMOTE_OFFHAND_WORKAROUND "disabled"
ENV GEYSER_DEFAULT_LOCALE "en_us"
ENV GEYSER_CACHE_IMAGES "0"
ENV GEYSER_ALLOW_CUSTOM_SKULLS "true"
ENV GEYSER_MAX_VISIBLE_CUSTOM_SKULLS "128"
ENV GEYSER_CUSTOM_SKULL_RENDERDISTANCE "32"
ENV GEYSER_ADD_NON_BEDROCK_ITEMS "true"
ENV GEYSER_ABOVE_BEDROCK_NETHER_BUILDING "false"
ENV GEYSER_FORCE_RESOURCE_PACKS "true"
ENV GEYSER_XBOX_ACHIEVEMENTS_ENABLED "false"
ENV GEYSER_LOG_PLAYER_IPS "true"
ENV GEYSER_NOTIFY_ON_UPDATE "true"
ENV GEYSER_UNUSABALE_SPACE_BLOCK "minecraft:barrier"

# Geyser Metrics Config
ENV GEYSER_METRICS_ENABLED "false"
ENV GEYSER_METRICS_UUID "generateduuid"

ENV GEYSER_MTU "1400"
ENV GEYSER_USE_DIRECT_CONNECTION "true"
ENV GEYSER_DISABLE_COMPRESSION "true"

RUN apt-get update && apt-get install -y gettext-base && rm -rf /var/lib/apt/lists/*

ADD https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/standalone /opt/Geyser.jar

COPY start.sh /usr/local/bin/start.sh
COPY config.yml.template /opt/config.yml.template

CMD /bin/bash /usr/local/bin/start.sh
